# Generated by Django 4.0.7 on 2022-08-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16)),
                ('rank', models.SmallIntegerField()),
                ('name', models.CharField(max_length=128)),
                ('logo_url', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('market_cap', models.BigIntegerField()),
                ('circulating_supply', models.BigIntegerField()),
                ('max_supply', models.BigIntegerField(null=True)),
                ('price_change_pct_1d', models.DecimalField(decimal_places=4, max_digits=9)),
                ('price_change_pct_7d', models.DecimalField(decimal_places=4, max_digits=9)),
                ('price_change_pct_30d', models.DecimalField(decimal_places=4, max_digits=9)),
                ('price_change_pct_365d', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
