# Generated by Django 4.0.7 on 2022-08-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'ordering': ['rank'], 'verbose_name_plural': 'Crypto currencies'},
        ),
    ]
